import type { RouteManifest } from './manifest.js';

function patternToName(pattern: string): string {
  if (pattern === '/') return 'home';
  const segments = pattern.split('/').filter(s => s);
  const camelCase = segments
    .map(seg => {
      if (seg.startsWith(':')) {
        const param = seg.slice(1);
        return param.charAt(0).toUpperCase() + param.slice(1);
      }
      return seg.charAt(0).toUpperCase() + seg.slice(1);
    })
    .join('');
  return camelCase.charAt(0).toLowerCase() + camelCase.slice(1);
}

function extractParams(pattern: string): string[] {
  return [...pattern.matchAll(/:([^/]+)/g)].map(m => m[1]);
}

export function generateTypedRoutes(manifest: RouteManifest): string {
  const lines: string[] = [
    '// Auto-generated by Kiln. Do not edit.',
    'export const routes = {',
  ];

  for (const page of manifest.pages) {
    const name = patternToName(page.pattern);
    const params = extractParams(page.pattern);
    if (params.length === 0) {
      lines.push(`  ${name}: '${page.pattern}',`);
    } else {
      const args = params.map(p => `${p}: string`).join(', ');
      const body = params.reduce(
        (pat, p) => pat.replace(`:${p}`, `\${${p}}`),
        page.pattern
      );
      lines.push(`  ${name}: (${args}) => \`${body}\`,`);
    }
  }

  lines.push('} as const;');
  lines.push('');
  lines.push('export type Routes = typeof routes;');
  return lines.join('\n');
}

export async function writeTypedRoutes(manifest: RouteManifest, outPath: string): Promise<void> {
  await Bun.write(outPath, generateTypedRoutes(manifest));
}
