export const packageJson = (name: string) => `{
  "name": "${name}",
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "kiln dev",
    "build": "kiln build",
    "start": "node dist/main.js"
  },
  "dependencies": {
    "@kiln/core": "workspace:*",
    "@kiln/react": "workspace:*",
    "@kiln/adapter-elysia": "workspace:*",
    "@kiln/engine": "workspace:*",
    "@kiln/routekit": "workspace:*",
    "elysia": "^1.0.12",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "ioredis": "^5.4.1"
  },
  "devDependencies": {
    "@kiln/cli": "workspace:*",
    "typescript": "^5.4.5",
    "vite": "^5.2.11",
    "@vitejs/plugin-react": "^4.2.1",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "@types/node": "^20.12.7"
  }
}
`;

export const tsconfigJson = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "jsx": "react-jsx",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "outDir": "./dist",
    "rootDir": "."
  },
  "include": ["src/**/*", "pages/**/*", "api/**/*", "kiln.config.ts"]
}
`;

export const kilnConfig = `import { defineConfig } from '@kiln/core';

export default defineConfig({
  port: 3000,
  pagesDir: './pages',
  apiDir: './api',
  fsr: {
    promoteAfterHits: 1,
    maxSseConnections: 1000,
    connectionTtlSecs: 3600,
    keepaliveSecs: 30,
    redisUrl: process.env.REDIS_URL || 'redis://localhost:6379',
    postgresUrl: process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/postgres'
  }
});
`;

export const layout = `import React from 'react';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Kiln Application</title>
        <script src="/_silcrow/silcrow.js" defer></script>
      </head>
      <body>
        <div id="app" data-ps-layout="/">
          {children}
        </div>
      </body>
    </html>
  );
}
`;

export const indexPage = `import type { SQL } from 'bun';
import React from 'react';
import { Live } from '@kiln/core';
import { useSilcrowForm } from '@kiln/react';

interface Todo {
  id: string;
  title: string;
  completed: boolean;
}

export const promoteAfter = 0;

export async function load() {
  return {
    todos: Live.list<Todo>({
      key: (todo) => todo.id,
      dependsOn: 'todo_events',
      query: async ({ sql }) => {
        const db = sql as SQL;
        return db<Todo[]>\`
          SELECT id::text, title, completed
          FROM todos
          ORDER BY id ASC
        \`;
      },
    }),
  };
}

export default function IndexPage({ todos }: Awaited<ReturnType<typeof load>>) {
  const form = useSilcrowForm('submit');

  return (
    <div style={{ fontFamily: 'sans-serif', padding: '2rem', maxWidth: '600px', margin: '0 auto' }}>
      <h1>Welcome to Kiln!</h1>
      <p style={{ color: '#666' }}>This is a new page generated by create-kiln.</p>

      <div style={{ border: '1px solid #ddd', padding: '1.5rem', borderRadius: '8px', marginTop: '2rem' }}>
        <h3>Live.list Example</h3>
        <ul>
          {todos.map((todo) => (
            <li key={todo.id}>
              <span>{todo.title}</span>{' '}
              <span>{todo.completed ? 'complete' : 'open'}</span>
            </li>
          ))}
        </ul>
      </div>
      
      <div style={{ border: '1px solid #ddd', padding: '1.5rem', borderRadius: '8px', marginTop: '2rem' }}>
        <h3>Server Action Example</h3>
        <form action={form.action}>
          <input 
            type="text" 
            name="name" 
            placeholder="Enter your name" 
            style={{ padding: '0.5rem', borderRadius: '4px', border: '1px solid #ccc', marginRight: '0.5rem' }}
          />
          <button 
            type="submit" 
            style={{ padding: '0.5rem 1rem', borderRadius: '4px', border: 'none', background: '#0070f3', color: 'white', cursor: 'pointer' }}
          >
            Submit
          </button>
        </form>
        {form.message && (
          <div style={{ marginTop: '1rem', color: '#0070f3', fontWeight: 'bold' }}>
            {form.message}
          </div>
        )}
      </div>
    </div>
  );
}

export const actions = {
  async submit(req: any) {
    const body = await req.formData();
    const name = body.get('name');
    return {
      message: \`Hello, \${name || 'stranger'}! Greetings from Elysia + Kiln server!\`
    };
  }
};
`;

export const healthApi = `export async function get(req: any) {
  return Response.json({ status: "ok" });
}
`;

export const migrationSql = `-- Create Kiln FSR table
CREATE TABLE IF NOT EXISTS kiln_fsr (
  route TEXT NOT NULL,
  slot TEXT NOT NULL DEFAULT '',
  query TEXT,
  query_params JSONB,
  depends_on TEXT[] NOT NULL DEFAULT '{}',
  stale BOOLEAN NOT NULL DEFAULT false,
  version INTEGER NOT NULL DEFAULT 0,
  hit_count INTEGER NOT NULL DEFAULT 0,
  promoted BOOLEAN NOT NULL DEFAULT false,
  tombstoned BOOLEAN NOT NULL DEFAULT false,
  promote_after INTEGER,
  debounce_secs INTEGER,
  html_path TEXT,
  json_path TEXT,
  column_name TEXT,
  last_hit TIMESTAMP,
  last_patched_at TIMESTAMP,
  CONSTRAINT kiln_fsr_pkey PRIMARY KEY (route, slot)
);

CREATE TABLE IF NOT EXISTS kiln_fsr_lists (
  route TEXT NOT NULL,
  name TEXT NOT NULL,
  depends_on TEXT[] NOT NULL DEFAULT '{}',
  rows JSONB NOT NULL DEFAULT '[]',
  stale BOOLEAN NOT NULL DEFAULT false,
  version INTEGER NOT NULL DEFAULT 0,
  html_path TEXT,
  json_path TEXT,
  last_patched_at TIMESTAMP,
  PRIMARY KEY (route, name)
);

CREATE TABLE IF NOT EXISTS todos (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS todo_events (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO todos (title, completed)
SELECT seed.title, seed.completed
FROM (VALUES
  ('Ship Live.list', false),
  ('Verify watcher patches', false)
) AS seed(title, completed)
WHERE NOT EXISTS (SELECT 1 FROM todos);

-- Invalidation function & trigger utility
CREATE OR REPLACE FUNCTION kiln_notify_change() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify(
    'kiln_invalidate',
    json_build_object('depKey', TG_ARGV[0], 'id', NEW.id)::text
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS todo_events_kiln_invalidate ON todo_events;
CREATE TRIGGER todo_events_kiln_invalidate
AFTER INSERT ON todo_events
FOR EACH ROW EXECUTE FUNCTION kiln_notify_change('todo_events');
`;

export const mainRunner = `import { startKiln } from '@kiln/routekit';
import { ElysiaAdapter } from '@kiln/adapter-elysia';
import { FsrStore, FsrWatcher, startDbNotificationPipeline } from '@kiln/engine';
import { SQL } from 'bun';
import config from '../kiln.config.js';

async function main() {
  const adapter = new ElysiaAdapter();

  // Initialize DB and FSR if credentials exist
  let fsr;
  let bunSql: SQL | null = null;
  const dbUrl = config.fsr?.postgresUrl;
  if (dbUrl) {
    bunSql = new SQL(dbUrl);
    const store = new FsrStore(bunSql);
    const watcher = new FsrWatcher(store, null, {
      pollIntervalMs: 1000,
      promoteAfterHits: config.fsr?.promoteAfterHits ?? 1,
      patchDebounceSecs: 0,
      purgeAfterSeconds: 3600,
      scheduledInvalidations: [],
      idleEvictSecs: 1800,
      idleThresholdSecs: 3600
    });
    
    await watcher.start();
    await startDbNotificationPipeline(dbUrl, store, watcher);
    fsr = { fsr: true, store, watcher };
    console.log('FSR baking engine and watcher successfully initialized.');
  }

  await startKiln(adapter, config, './pages', fsr);

  const port = config.port || config.web?.port || 3000;
  await adapter.listen(port, () => {
    console.log(\`Server booted successfully on http://localhost:\${port}\`);
  });
}

main().catch(err => {
  console.error('Fatal startup error:', err);
  process.exit(1);
});
`;
